name: Manual Build
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          arch: arm64
          runner: macos-latest
          expander_leg: macos-latest--arm64
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK
      uses: actions/setup-java@v6
      with:
        java-version: '25'
        distribution: 'corretto'
        cache: maven
    - name: Validate formatting (Spotless)
      run: ./mvnw --batch-mode spotless:check
    - name: Build
      run: |
        ./integration_test_suite/pull-smoke-test-docker-images.sh
        JAVA_DOCKER_IMAGES=SMOKE PROMETHEUS_DOCKER_IMAGES=SMOKE ./mvnw --batch-mode clean install

    name: Build [${{ matrix.expander_leg }}]
    timeout-minutes: 150
